@url = 'http://localhost:3000/'

GET http://localhost:3000/flights HTTP/1.1  //GET ALL FLIGHTS

###
GET http://localhost:3000/flights/ HTTP/1.1    //GET SINGLE FLIGHT(INCLUDE FLIGHT ID IN URL)

###
POST http://localhost:3000/flights HTTP/1.1  //BOOK FLIGHT
Content-Type: application/json

{
    "title": "Flight to Canada",
    "time": "1pm",
    "price": 26000,
    "date": "26-6-2022"
}

###
PUT http://localhost:3000/flights/ HTTP/1.1    //UPDATE FLIGHT(INCLUDE FLIGHT ID IN URL)
Content-Type: application/json

{
    "title": "Flight to London",
    "time": "10pm",
    "price": 26000,
    "date": "26-6-2022"
}

###
DELETE http://localhost:3000/flights/ HTTP/1.1    //DELETE FLIGHT(INCLUDE FLIGHT ID IN URL)
